Monster.create(name: "Spider", description: "A huge spider", hitpoints: 14, strength: 8, x_coord: 0, y_coord: 2, alive: true)
Monster.create(name: "Skorpion", description: "Skorpions can sting", hitpoints: 13, strength: 10, x_coord: 2, y_coord: 1, alive: true)
Monster.create(name: "Rat", description: "Rat's sometimes carry disease", hitpoints: 8, strength: 9, x_coord: 3, y_coord: -1, alive: true)
Monster.create(name: "Possum", description: "A large possum", hitpoints: 12, strength: 10, x_coord: 1, y_coord: -2, alive: true)
Monster.create(name: "Roach", description: "Roaches are quick and some fly", hitpoints: 8, strength: 6, x_coord: 3, y_coord: 1, alive: true)
Monster.create(name: "Dog", description: "A large dangerous looking dog", hitpoints: 27, strength: 3, x_coord: 1, y_coord: -1, alive: true)
Monster.create(name: "Mouse", description: "Don't let the small size of the mouse fool you", hitpoints: 9, strength: 11, x_coord: 3, y_coord: 0, alive: true)
Monster.create(name: "Large Mouse", description: "This is a really large mouse", hitpoints: 11, strength: 12, x_coord: 2, y_coord: 0, alive: true)
Monster.create(name: "Limp pigeon", description: "It's a pigeon, but it doesn't fly anymore", hitpoints: 8, x_coord: -1, y_coord: 0, alive: true)
Monster.create(name: "Limp Dog", description: "It's an old shaggy dog that seems to be linping", hitpoints: 7, x_coord: -2, y_coord: 0, alive: true)
